// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBft5HQuHvX1qmBSypYjzpZcNTXOvcN3Kc',
    appId: '1:1029391195659:web:5b0d9cb0a4d8c97c98b10e',
    messagingSenderId: '1029391195659',
    projectId: 'whatbytesassessment',
    authDomain: 'whatbytesassessment.firebaseapp.com',
    storageBucket: 'whatbytesassessment.firebasestorage.app',
    measurementId: 'G-LPGY4LYBLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJAeZlnHAx2y77Y9X_IqDl9XvQEt6F7g',
    appId: '1:1029391195659:android:f044ebaf5ec8109098b10e',
    messagingSenderId: '1029391195659',
    projectId: 'whatbytesassessment',
    storageBucket: 'whatbytesassessment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVd3ZcC6EEesbQblASaT8YXWvWXRH74Iw',
    appId: '1:1029391195659:ios:2e89a42e2e47d7b698b10e',
    messagingSenderId: '1029391195659',
    projectId: 'whatbytesassessment',
    storageBucket: 'whatbytesassessment.firebasestorage.app',
    iosBundleId: 'com.example.whatbytesAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVd3ZcC6EEesbQblASaT8YXWvWXRH74Iw',
    appId: '1:1029391195659:ios:2e89a42e2e47d7b698b10e',
    messagingSenderId: '1029391195659',
    projectId: 'whatbytesassessment',
    storageBucket: 'whatbytesassessment.firebasestorage.app',
    iosBundleId: 'com.example.whatbytesAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBft5HQuHvX1qmBSypYjzpZcNTXOvcN3Kc',
    appId: '1:1029391195659:web:d0137c75156858d198b10e',
    messagingSenderId: '1029391195659',
    projectId: 'whatbytesassessment',
    authDomain: 'whatbytesassessment.firebaseapp.com',
    storageBucket: 'whatbytesassessment.firebasestorage.app',
    measurementId: 'G-HTQKJ2038E',
  );
}
